### ISSUE TITLE
 Problems iwht ktImportBlast with Blastx results and updateAccessions.sh

### ISSUE THREAD

**Issue by SerafinGut** [marbl/Krona#26] opened 2016-11-28 16:07 UTC
I get empty html files when using ktImportBlast with Blastx results whereas the same tool works fine with blastn results. I thought it was an accession-list problem and I tried to update accessions with updateAccessions.sh. However, I got an error message: 

Sorting dead_nucl.accession2taxid.gz...
Sorting dead_prot.accession2taxid.gz...
Sorting dead_wgs.accession2taxid.gz...
Sorting nucl_est.accession2taxid.gz...
Sorting nucl_gb.accession2taxid.gz...
Sorting nucl_gss.accession2taxid.gz...
Sorting nucl_wgs.accession2taxid.gz...
Sorting prot.accession2taxid.gz...
make: sort: write failed: /tmp/sortpErLfH: No space left on device 
*** [prot.accession2taxid.sorted] Error 2

Any idea of what I am doing wrong please?

**Comment by WardDeb** [comment] 2017-01-10 10:55
Seems to be 2 different problems here, 1 is it seems like your diskspace is full. 
The other problem, with the empty html files, we had as well. No idea what the cause was but a reinstallation of kronatools, and a new database fixed the problem.

**Comment by ondovb** [comment] 2017-01-13 13:53
@WardDeb is correct; you will simply need more room on your hard drive to update the accessions, specifically ~17GB of scratch space for the formatting, in addition to the ~17GB taken up by the formatted accession database (which will just be overwritten if one exists).

As to the empty HTML files, I haven't seen a problem like this and would be curious about any errors/warnings that accompany them, or examples of the data that cause them.

**Comment by ondovb** [comment] 2017-01-13 13:55
Also, if it will help with space, you can specify where the database is kept by running `install.pl` again with `--taxonomy <path>`.

**Comment by WardDeb** [comment] 2017-01-13 14:39
@ondovb The problem with empty HTML files was for us unclear. It only happened with certain blast outputs and is not entirely reproducable. Also, at least for us, no errors or warnings were generated during the making of these files. I've added a screenshot with the opened html file. If I open the counts, the list of hits  is there, so somehow the information is in there.. Hope this helps.
[http://imgur.com/a/3tDCk](url)

**Comment by ondovb** [comment] 2017-01-13 15:41
@WardDeb Yes, that is helpful. Probably a JavaScript error is preventing the data from being rendered (which would show up in the browser's developer console). If you wouldn't mind passing along any such errors, or just the HTML file itself, the next time this crops up, that should help me figure this out. Thanks!

**Comment by WardDeb** [comment] 2017-01-13 17:01
@ondovb I've opened the developer console, and it seems like there are alot of errors popping up. I'm not familiar with JavaScript so to me it is difficult to make sense of it. I've added the HTML file in this message. Thanks for the effort!
[tester.zip](https://github.com/marbl/Krona/files/704853/tester.zip)

**Comment by ondovb** [comment] 2017-01-13 17:14
@WardDeb In this case the particular issue seems to be that everything is assigned to Root, which Krona has never handled, but should (issue #29 opened for this). As far as reproducibility, I would not expect this to be random, but it could be fixed by updating the DB if more things get properly assigned instead of going to Root.

**Comment by WardDeb** [comment] 2017-01-17 09:37
@ondovb I've asked a colleague of mine for another chart. I didn't have this problem a lot of times but in this example the file can be viewed when downloaded locally, but when we host the on our cluster and try to visualize over the internet, it doesn't (other charts worked fine). That's the reason why I called it random. Thanks for taking the time to look at this!
[Egel1.zip](https://github.com/marbl/Krona/files/710526/Egel1.zip)

**Comment by ondovb** [comment] 2017-02-08 05:32
I think the original problems here are either resolved or can be traced to #29. This latest file seems to work for me, but feel free to file new issues if any more information comes up regarding blank charts.

**Closed by ondovb** 2017-02-08 05:32 UTC
