### ISSUE TITLE
Krona.html is not opening 

### ISSUE THREAD

**Issue by Bijishibulal** [marbl/Krona#22] opened 2016-10-16 18:21 UTC
Krona.html is not opening . I am getting message as :Could not get resources from "http://krona.sourceforge.net".

The same happened 1 week ago. but it was fine after 2 days.
Again the same issue. I would like to get this rectified at the earliest.

**Comment by khyox** [comment] 2016-10-16 18:27
Which release of Krona are you using? Are you working with the last stable release (v2.7)?

**Comment by Bijishibulal** [comment] 2016-10-16 18:39
Krona excel template 2.2. Actually I am new to this software. I got some soil samples analyzed by one of the research institute in Texas. They have sent the report as xlsm. I just downloaded the krona zip file from github and installed windows version.

**Comment by Bijishibulal** [comment] 2016-10-16 18:52
https://github.com/marbl/Krona/releases
Installed Krona 2.7. Got the message Installation complete. 
Still getting message as :Could not get resources from "http://krona.sourceforge.net".

**Comment by khyox** [comment] 2016-10-16 19:10
As Krona seems to be moving to GitHub from Sourceforge I guess that some code that could search for resources in the Sourceforge website could be failing now. 

I see that KronaTools-2.7.tar from [Krona releases](https://github.com/marbl/Krona/releases) is not containing ExcelTemplate. I have never used ExcelTemplate so I am afraid I cannot figure out the cause of your trouble. 

Anyway, I guess your next step could be to clone the git repo and try to use the template directly from there, as it should be the most updated version. Another choice would be to download the last version available from Sourceforge ([Krona ExcelTemplate 2.3](https://sourceforge.net/projects/krona/files/Excel%20template%20%28Windows%2C%20Mac%20with%20MS%20Office%29/KronaExcelTemplate-2.3.zip/download)) but I would recommend the former approach so that if the template still fails, it could be easily addressed by the developers.

**Comment by Bijishibulal** [comment] 2016-10-16 19:13
Ok. Thanks . Let me try to clone the git repo.

**Comment by Bijishibulal** [comment] 2016-10-16 19:51
I could not  clone the git repo, as I am new to this. Krona excel template 2.3 also giving me the same message. I sit possible to send you the xlsm file ? Can you please send me your mail id at bijisd@gmail.com

**Comment by khyox** [comment] 2016-10-16 20:22
Sorry, as I told you, I have never used ExcelTemplate. Furthermore, I am not using Excel in my GNU/Linux boxes, as it is proprietary software and there are amazing alternatives. Don't worry, all of us have been new one day. You have instructions to clone a github repository [here](https://help.github.com/articles/cloning-a-repository/) and more general instructions [here](https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository).

**Comment by Bijishibulal** [comment] 2016-10-16 20:24
Okay. Ill try to get this done. Thanks

**Comment by ondovb** [comment] 2016-10-19 15:09
The latest release, [2.4](https://github.com/marbl/Krona/releases/tag/xl2.4), creates self-contained charts and should solve this problem.

**Comment by Bijishibulal** [comment] 2016-10-19 18:36
Thanks for your reply.

**Comment by Bijishibulal** [comment] 2016-10-20 06:08
**# @ondovb , It worked as per your suggestion. Thanks a lot....**

**Closed** 2016-10-20 14:22 UTC
